### List all tickets

GET http://localhost:8080/api/tickets
Accept: application/json

### Find ticket by id

GET http://localhost:8080/api/tickets/1
Accept: application/json

### Buy ticket

POST http://localhost:8080/api/tickets
Content-Type: application/json

{
  "trainId" : 1,
  "passengerId" : 1
}

### Delete ticket by id

DELETE http://localhost:8080/api/tickets/1

### Delete all tickets

DELETE http://localhost:8080/api/tickets